name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Compile and Run Tests
      run: g++ -std=c++20 -g -o crdt tests.cpp && ./crdt